#ifndef SFML_TEMPLATE_CONSTANTS_HPP
#define SFML_TEMPLATE_CONSTANTS_HPP

constexpr int GRIDSIZE = 20; // size of each cell
constexpr int WIDTHGRID = 800/GRIDSIZE, HEIGHTGRID = 600/GRIDSIZE;

#endif //SFML_TEMPLATE_CONSTANTS_HPP
