#ifndef SFML_TEMPLATE_CONSTANTS_HPP
#define SFML_TEMPLATE_CONSTANTS_HPP

constexpr int WIDTHWINDOW = 460, HEIGHTWINDOW = 460;
const int GRIDSIZE = 20;
constexpr int WIDTHGRID = (WIDTHWINDOW-100)/GRIDSIZE, HEIGHTGRID = (HEIGHTWINDOW-100)/GRIDSIZE;

#endif //SFML_TEMPLATE_CONSTANTS_HPP
