#ifndef SFML_TEMPLATE_CONSTANTS_HPP
#define SFML_TEMPLATE_CONSTANTS_HPP

constexpr int WIDTHWINDOW = 450, HEIGHTWINDOW = 500;
const int GRIDSIZE = 50;
constexpr int WIDTHGRID = WIDTHWINDOW/GRIDSIZE, HEIGHTGRID = (HEIGHTWINDOW-100)/GRIDSIZE;

#endif //SFML_TEMPLATE_CONSTANTS_HPP
